{"sections":[],"abstract":[{"type":"text","text":"“Internal” error in external application."},{"type":"text","text":" "},{"type":"text","text":"Third-party API or service failure, unexpected behavior, …"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/external","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"external"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swifterrorkit\/sourceerrorattribute\/external"]}],"metadata":{"symbolKind":"case","role":"symbol","externalID":"s:13SwiftErrorKit06SourceB9AttributeO8externalyA2CmF","roleHeading":"Case","title":"SourceErrorAttribute.external","modules":[{"name":"SwiftErrorKit"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"external","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute"]]},"references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute":{"url":"\/documentation\/swifterrorkit\/sourceerrorattribute","abstract":[{"type":"text","text":"An error attribute to include information about the high-level component"},{"type":"text","text":" "},{"text":"in which the error emerged.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SourceErrorAttribute"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceErrorAttribute"}],"title":"SourceErrorAttribute","role":"symbol"},"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"title":"SwiftErrorKit","url":"\/documentation\/swifterrorkit","type":"topic","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","kind":"symbol","abstract":[{"text":"Error attribution and commons.","type":"text"}],"role":"collection"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/external":{"title":"SourceErrorAttribute.external","kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/external","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"external"}],"abstract":[{"type":"text","text":"“Internal” error in external application."},{"type":"text","text":" "},{"type":"text","text":"Third-party API or service failure, unexpected behavior, …"}],"type":"topic","role":"symbol","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/external"}}}