{"variants":[{"paths":["\/documentation\/swifterrorkit\/sourceerrorattribute\/external"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"roleHeading":"Case","role":"symbol","modules":[{"name":"SwiftErrorKit"}],"title":"SourceErrorAttribute.external","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"external"}],"externalID":"s:13SwiftErrorKit06SourceB9AttributeO8externalyA2CmF"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"“Internal” error in external application."},{"type":"text","text":" "},{"type":"text","text":"Third-party API or service failure, unexpected behavior, …"}],"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute"]]},"identifier":{"url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/external","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"external","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute":{"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","kind":"symbol","abstract":[{"text":"An error attribute to include information about the high-level component","type":"text"},{"type":"text","text":" "},{"type":"text","text":"in which the error emerged."}],"role":"symbol","title":"SourceErrorAttribute","url":"\/documentation\/swifterrorkit\/sourceerrorattribute","navigatorTitle":[{"kind":"identifier","text":"SourceErrorAttribute"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceErrorAttribute"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/external":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"external"}],"role":"symbol","title":"SourceErrorAttribute.external","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/external","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/external","kind":"symbol","abstract":[{"type":"text","text":"“Internal” error in external application."},{"type":"text","text":" "},{"type":"text","text":"Third-party API or service failure, unexpected behavior, …"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","abstract":[{"type":"text","text":"Error attribution and commons."}],"type":"topic","title":"SwiftErrorKit","kind":"symbol","role":"collection","url":"\/documentation\/swifterrorkit"}}}