{"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"external","kind":"identifier"}],"symbolKind":"case","externalID":"s:13SwiftErrorKit06SourceB9AttributeO8externalyA2CmF","title":"SourceErrorAttribute.external","roleHeading":"Case","role":"symbol","modules":[{"name":"SwiftErrorKit"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"“Internal” error in external application.","type":"text"},{"type":"text","text":" "},{"text":"Third-party API or service failure, unexpected behavior, …","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"external"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/external"},"kind":"symbol","variants":[{"paths":["\/documentation\/swifterrorkit\/sourceerrorattribute\/external"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute"]]},"references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"title":"SwiftErrorKit","abstract":[{"text":"Error attribution and commons.","type":"text"}],"kind":"symbol","url":"\/documentation\/swifterrorkit","type":"topic","role":"collection","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute":{"role":"symbol","abstract":[{"text":"An error attribute to include information about the high-level component","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"in which the error emerged."}],"type":"topic","title":"SourceErrorAttribute","url":"\/documentation\/swifterrorkit\/sourceerrorattribute","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","navigatorTitle":[{"kind":"identifier","text":"SourceErrorAttribute"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceErrorAttribute","kind":"identifier"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/external":{"abstract":[{"text":"“Internal” error in external application.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Third-party API or service failure, unexpected behavior, …"}],"kind":"symbol","title":"SourceErrorAttribute.external","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/external","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/external","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"external"}]}}}