{"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"external"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swifterrorkit\/sourceerrorattribute\/external"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/external"},"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"external","kind":"identifier"}],"modules":[{"name":"SwiftErrorKit"}],"roleHeading":"Case","externalID":"s:13SwiftErrorKit06SourceB9AttributeO8externalyA2CmF","symbolKind":"case","title":"SourceErrorAttribute.external","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"“Internal” error in external application.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Third-party API or service failure, unexpected behavior, …"}],"references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute":{"url":"\/documentation\/swifterrorkit\/sourceerrorattribute","role":"symbol","navigatorTitle":[{"text":"SourceErrorAttribute","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"An error attribute to include information about the high-level component"},{"text":" ","type":"text"},{"text":"in which the error emerged.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SourceErrorAttribute","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","title":"SourceErrorAttribute"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/external":{"title":"SourceErrorAttribute.external","role":"symbol","type":"topic","abstract":[{"type":"text","text":"“Internal” error in external application."},{"type":"text","text":" "},{"type":"text","text":"Third-party API or service failure, unexpected behavior, …"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"external","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/external","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/external"},"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"type":"topic","role":"collection","abstract":[{"type":"text","text":"Error attribution and commons."}],"url":"\/documentation\/swifterrorkit","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","kind":"symbol","title":"SwiftErrorKit"}}}