{"sections":[],"abstract":[{"type":"text","text":"“Internal” error in external application."},{"type":"text","text":" "},{"text":"Third-party API or service failure, unexpected behavior, …","type":"text"}],"variants":[{"paths":["\/documentation\/swifterrorkit\/sourceerrorattribute\/external"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute"]]},"identifier":{"url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/external","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"SwiftErrorKit"}],"roleHeading":"Case","symbolKind":"case","title":"SourceErrorAttribute.external","externalID":"s:13SwiftErrorKit06SourceB9AttributeO8externalyA2CmF","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"external"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"external"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute":{"kind":"symbol","type":"topic","title":"SourceErrorAttribute","abstract":[{"type":"text","text":"An error attribute to include information about the high-level component"},{"text":" ","type":"text"},{"type":"text","text":"in which the error emerged."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SourceErrorAttribute","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","url":"\/documentation\/swifterrorkit\/sourceerrorattribute","navigatorTitle":[{"kind":"identifier","text":"SourceErrorAttribute"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/external":{"kind":"symbol","title":"SourceErrorAttribute.external","type":"topic","abstract":[{"type":"text","text":"“Internal” error in external application."},{"type":"text","text":" "},{"type":"text","text":"Third-party API or service failure, unexpected behavior, …"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"external","kind":"identifier"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/external","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/external"},"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"kind":"symbol","role":"collection","title":"SwiftErrorKit","url":"\/documentation\/swifterrorkit","abstract":[{"type":"text","text":"Error attribution and commons."}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","type":"topic"}}}