{"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`internal`"}],"symbolKind":"case","externalID":"s:13SwiftErrorKit06SourceB9AttributeO8internalyA2CmF","title":"SourceErrorAttribute.internal","roleHeading":"Case","role":"symbol","modules":[{"name":"SwiftErrorKit"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Error in internal application."},{"text":" ","type":"text"},{"type":"text","text":"Logic error, bug, or issue with internal operation, …"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`internal`"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/internal","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/swifterrorkit\/sourceerrorattribute\/internal"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute"]]},"references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute":{"role":"symbol","abstract":[{"text":"An error attribute to include information about the high-level component","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"in which the error emerged."}],"type":"topic","title":"SourceErrorAttribute","url":"\/documentation\/swifterrorkit\/sourceerrorattribute","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","navigatorTitle":[{"kind":"identifier","text":"SourceErrorAttribute"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceErrorAttribute","kind":"identifier"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/internal":{"abstract":[{"type":"text","text":"Error in internal application."},{"type":"text","text":" "},{"text":"Logic error, bug, or issue with internal operation, …","type":"text"}],"kind":"symbol","title":"SourceErrorAttribute.internal","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/internal","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/internal","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`internal`"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"title":"SwiftErrorKit","abstract":[{"text":"Error attribution and commons.","type":"text"}],"kind":"symbol","url":"\/documentation\/swifterrorkit","type":"topic","role":"collection","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit"}}}