{"metadata":{"modules":[{"name":"SwiftErrorKit"}],"roleHeading":"Case","externalID":"s:13SwiftErrorKit06SourceB9AttributeO8internalyA2CmF","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`internal`","kind":"identifier"}],"title":"SourceErrorAttribute.internal"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/swifterrorkit\/sourceerrorattribute\/internal"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`internal`","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Error in internal application."},{"type":"text","text":" "},{"text":"Logic error, bug, or issue with internal operation, …","type":"text"}],"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/internal"},"kind":"symbol","references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute":{"navigatorTitle":[{"kind":"identifier","text":"SourceErrorAttribute"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"An error attribute to include information about the high-level component","type":"text"},{"text":" ","type":"text"},{"text":"in which the error emerged.","type":"text"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceErrorAttribute"}],"url":"\/documentation\/swifterrorkit\/sourceerrorattribute","title":"SourceErrorAttribute"},"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","title":"SwiftErrorKit","role":"collection","abstract":[{"type":"text","text":"Error attribution and commons."}],"url":"\/documentation\/swifterrorkit"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/internal":{"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/internal","type":"topic","abstract":[{"type":"text","text":"Error in internal application."},{"type":"text","text":" "},{"text":"Logic error, bug, or issue with internal operation, …","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"`internal`","kind":"identifier"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/internal","title":"SourceErrorAttribute.internal"}}}